<?php
$host = "localhost";
$username = "root";
$password = "htmlyu";
$database = "data_siswa";

$koneksi = mysqli_connect($host, $username, $password, $database);

if (!$koneksi) {
    die("Koneksi database gagal: " . mysqli_connect_error());
}


if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST["username"];
    $password = $_POST["password"];

    $query = "SELECT * FROM user WHERE username = '$username' AND password = '$password'";
    $result = mysqli_query($koneksi, $query);

    if (mysqli_num_rows($result) == 1) {
        
        session_start();
        $_SESSION["username"] = $username;
        header("Location: admin.html"); //
    } else {
        
        echo "Login gagal. Silakan coba lagi.";
    }

    mysqli_close($koneksi);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            
        }
        

        .header h2 {
            margin-bottom: 30px;
            color: white;
            text-align: center;
            text-shadow: 2px 2px 2px black;
            font-size: 27px;
            padding: 5px 10px;
            background-color: aqua;
            border-radius: 50px;
            box-shadow: 1px 1px 1px 1px black;
        }

        .container {
        max-width: 500px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        position: relative; /* Add position relative for responsive delete button */
    }

    label {
        display: block;
        margin-bottom: 10px;
        color: #555;
        font-weight: bold;
        -webkit-animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }

    input,
    select {
        width: 100%;
        padding: 12px;
        margin-bottom: 20px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

        button {
            background-color: aqua;
            color: white;
            padding: 10px 50px;
            border: none;
            cursor: pointer;
            border-radius: 5px;
            text-shadow: 2px 2px 2px black;
            font-size: 18px;
            margin-left: 100px;
            -webkit-animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        }

        button:hover {
            background-color: rgb(59, 224, 224);
        }

        a {
            text-decoration: none;
            color: #007BFF;
        }

        a:hover {
            text-decoration: underline;
        }

        .container p {
            text-align: center;
            -webkit-animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        }

        /* ----------------------------------------------
 * Generated by Animista on 2024-1-7 10:30:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
            transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
            transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}


        header {
            padding: 15px;
            background-color: aqua;
            border-radius: 30px;
            text-align: center;
            -webkit-animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        }

        h2 {
            color: white;
            text-shadow: 1px 1px 1px black;
            margin: 0;
            -webkit-animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        }

        .logo-container {
            display: flex;
            justify-content: center;
            margin-top: 10px;
        }

        img {
            max-width: 80px; /* Sesuaikan dengan kebutuhan */
            height: auto;
            margin: 0 10px; /* Jarak antar foto */
        }
        footer {
        padding: 20px;
        background-color: aqua;
        color: #fff;
    }
    .container h3 {
        text-align: center;
        -webkit-animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 2s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2024-1-7 10:24:33
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

    footer a {
        text-decoration: none;
        color: #fff;
        text-shadow: 1px 1px 1px black;
    }

    footer p {
        text-align: center;
        color: #fff;
        font-size: 15px;
        text-shadow: 1px 1px 1px black;
    }
    span {
        font-size: 20px;
    }

    .dev {
        text-shadow: 1px 1px 1px black;
    }
    @media only screen and (max-width: 600px) {
        form {
            max-width: 100%;
        }

        

        
    }
    </style>
</head>
<body>
<header>
        <h2>Bk Smkn 1 Rangkasbitung
           <br> <span>ADMIN</span>
        </h2>
    </header>
    <div class="logo-container">
        <img src="tkj (2).jpeg" alt="Logo 1">
        <img src="logo_skensa-removebg-preview (1).png" alt="Logo 2">
        <img src="bisa-removebg-preview.png" alt="Logo 1">
    </div>
    <div class="container">
        <h3>Selamat Datang!</h3>
        <p>Verifikasi bahwa kamu adalah admin</p>
        <hr>
        
        <form action="admin.php" method="post">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" placeholder="Username Admin" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" placeholder="Password Admin" required>
       <button type="submit">Login</button>
        </form>
    </div>
  